version: "3"
services:
  db:
    image: spring-mss-db
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "db:/var/lib/postgresql/data"
volumes:
  db: