server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://service-auth
          predicates:
            - Path=/api/auth/**
        - id: user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
        - id: order
          uri: lb://service-order
          predicates:
            - Path=/api/order/**
auth:
  secret: ${AUTH_SECRET:1234567890qwertyuiopasdfghjklzxcvbnm}