server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
        - id: order
          uri: lb://service-order
          predicates:
            - Path=/api/order/**